services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_CLIENT_CALLBACK_URL=${GOOGLE_CLIENT_CALLBACK_URL}
        - API_PORT=${API_PORT}
        - COOKIE_DOMAIN=${COOKIE_DOMAIN}
        - WEB_BASE_URL=${WEB_BASE_URL}
        - FILE_KEY_PRIVATE=${FILE_KEY_PRIVATE}
        - FILE_KEY_PUBLIC=${FILE_KEY_PUBLIC}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "${API_PORT}:${API_PORT}"
    image: "gcr.io/${GOOGLE_PROJECT_ID}/${ENV}api" 
    command: go run .
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /app
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: "gcr.io/${GOOGLE_PROJECT_ID}/${ENV}web" 
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app