# Use the latest LTS version of Node.js
FROM node:18-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY ./web/package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the rest of your application files
COPY ./web .
COPY ./docs/high-level-arch.png /app/public/

ARG API_BASE_URL
ENV API_BASE_URL=$API_BASE_URL
ARG NODE_API_BASE_URL
ENV NODE_API_BASE_URL=${NODE_API_BASE_URL}

# Make executable
RUN chmod +x ./run_web.sh
RUN ./run_web.sh

# Run the app
CMD ["npm", "start"]