services:
  api:
    env_file:
      - ${ENV_PATH}
    build:
      context: ./api
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "${API_PORT}:${API_PORT}"
    image: "gcr.io/${GOOGLE_PROJECT_ID}/${ENV}api" 
  frontend:
    env_file:
      - ${ENV_PATH}
    build:
      context: ./web
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: "gcr.io/${GOOGLE_PROJECT_ID}/${ENV}web" 
    ports:
      - "${WEB_PORT}:${WEB_PORT}"